export const Products = [
    {
      id: 1,
      title: "Malla cremita",
      precio: 3000,
      description: "Tela de muy buena calidad, 100 algodon",
      img: "https://res.cloudinary.com/drgvqeadn/image/upload/v1680489038/malla_cremita_gyngef.jpg",
      stock: 10,
      quanty: 1,
    },
    {
      id: 2,
      title: "Malla Celeste",
      precio: 3000,
      description: "Tela de muy buena calidad, 100 algodon",
      img: `https://res.cloudinary.com/drgvqeadn/image/upload/v1680489038/mallaceleste_j2asxg.jpg`,
      stock: 10,
      quanty: 1,
    },
    {
      id: 3,
      title: "Malla Marron",
      precio: 3000,
      description: "Tela de muy buena calidad, 100 algodon",
      img: `https://res.cloudinary.com/drgvqeadn/image/upload/v1680489037/mallamarron_kt8ujq.jpg`,
      stock: 10,
      quanty: 1,
    },
    {
      id: 4,
      title: "Malla Roja",
      precio: 3000,
      description: "Tela de muy buena calidad, 100 algodon",
      img: `https://res.cloudinary.com/drgvqeadn/image/upload/v1680489037/mallaroja_iq31tf.jpg`,
      stock: 10,
      quanty: 1,
    },
    {
      id: 5,
      title: "Malla Rosa",
      precio: 3500,
      description: "Tela de muy buena calidad, 100 algodon",
      img: `https://res.cloudinary.com/drgvqeadn/image/upload/v1680489038/mallarosa_bhx2bn.jpg`,
      stock: 10,
      quanty: 1,
    },
    {
      id: 6,
      title: "Malla Violeta",
      precio: 3500,
      description: "Tela de muy buena calidad, 100 algodon",
      img: `https://res.cloudinary.com/drgvqeadn/image/upload/v1680489038/mallavioleta_gcfh5a.jpg`,
      stock: 10,
      quanty: 1,
    },
    {
      id: 7,
      title: "Malla Tigre",
      precio: 3500,
      description: "Tela de muy buena calidad, 100 algodon",
      img: `https://res.cloudinary.com/drgvqeadn/image/upload/v1680489038/mallatigre_yjwpet.jpg`,
      stock: 10,
      quanty: 1,
    },
  
    {
      id: 8,
      title: "Conjunto negro y rosa",
      precio: 3000,
      description: "Tela de muy buena calidad, 100 algodon",
      img: `https://res.cloudinary.com/drgvqeadn/image/upload/v1680489033/cojuntonegroyrosa_h3vqza.jpg`,
      stock: 10,
      quanty: 1,
    },
    {
      id: 9,
      title: "Conjunto negro y blanco",
      precio: 3000,
      description: "Tela de muy buena calidad, 100 algodon",
      img: `https://res.cloudinary.com/drgvqeadn/image/upload/v1680489035/colaesnegrayblanca_dm5cor.jpg`,
      stock: 10,
      quanty: 1,
    },
    {
      id: 10,
      title: "Colales Rojo",
      precio: 3000,
      description: "Tela de muy buena calidad, 100 algodon",
      img: `https://res.cloudinary.com/drgvqeadn/image/upload/v1680489034/colalesornellaroja_not14o.jpg`,
      stock: 10,
      quanty: 1,
    },
    {
      id: 11,
      title: "Colales Amarilla",
      precio: 3000,
      description: "Tela de muy buena calidad, 100 algodon",
      img: `https://res.cloudinary.com/drgvqeadn/image/upload/v1680489035/colalesamarilla_mbeqfq.jpg`,
      stock: 10,
      quanty: 1,
    },
    {
      id: 12,
      title: "Colales Azul",
      precio: 3500,
      description: "Tela de muy buena calidad, 100 algodon",
      img: `https://res.cloudinary.com/drgvqeadn/image/upload/v1680489034/colalesazul_r0is24.jpg`,
      stock: 10,
      quanty: 1,
    },
    {
      id: 13,
      title: "Colales Blanca",
      precio: 3500,
      description: "Tela de muy buena calidad, 100 algodon",
      img: `https://res.cloudinary.com/drgvqeadn/image/upload/v1680489035/colalesblanca_xqxlsd.jpg`,
      stock: 10,
      quanty: 1,
    },
    {
      id: 14,
      title: "Colales Negra",
      precio: 3500,
      description: "Tela de muy buena calidad, 100 algodon",
      img: `https://res.cloudinary.com/drgvqeadn/image/upload/v1680489034/colalesnegra_c89w1u.jpg`,
      stock: 10,
      quanty: 1,
    },
  ];
  